server.port: 8080
eureka.client.serviceUrl.defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
eureka.client.instance.preferIpAddress: true
spring:
  cloud:
    gateway:
      routes:
      - id: studentservice
        uri: lb://STUDENT-SERVICE/
        predicates:
        - Path=/student/**
      - id: teacherservice
        uri: lb://TEACHER-SERVICE/
        predicates:
        - Path=/teacher/**
      - id: batchservice
        uri: lb://BATCH-SERVICE/
        predicates:
        - Path=/batch/**
  zipkin:
    baseUrl: http://localhost:9411/